name: Node CI

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install and lint
        run: |
          npm ci
          npm run test:other
          npm run test:code
          npm run test:typecheck
        env:
          CI: true
